### ISSUE TITLE
Issue with IOS 14

### ISSUE THREAD

**Issue by AS903** [sjy234sjy234/KinectFusion-ios#6]
Hello! I am new to developing and I have just been playing around with the code for fun.  I have been trying your implementation, which has been working great until I updated my iphone to IOS 14.  I have suddenly been receiving the output of: 

CAMetalLayer ignoring invalid setDrawableSize width=0.000000 height=0.000000
first frame, fusion reset
Lost frame
Fusion Failed

I was wondering if you have any idea why this is happening and how I could fix it? 

Thank you so much! And thank you for your amazing work!

**Comment by sjy234sjy234** [comment]
This is mainly caused by ios's stricter shader language update. You can try to locate some "nan“ or "float compare" related code in shaders and add some safer "if" logic before it to avoid "nan" or "float compare" problems. 
It would be very appreciated if you push the fixed version code after you solve the problem.

**Comment by AS903** [comment]
Hello! Sorry it took me so long to respond to your message! Unfortunately, my computer died and it took a while for me to have access to a replacement.  I am going to close the issue and will start working on it once I have time again.  

Thank you so much for your help!
